### ISSUE TITLE
I can't download my record 

### ISSUE THREAD

**Issue by boubakerBS** [pi-ra/beesy-issue-tracker#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

![image](https://github.com/pi-ra/beesy-issue-tracker/assets/141621437/fcb6da11-5b09-4595-bad9-d31b215abaf0)
if i click download for the second record ( the browser page is crashed 

### Steps To Reproduce

j![image](https://github.com/pi-ra/beesy-issue-tracker/assets/141621437/fcb6da11-5b09-4595-bad9-d31b215abaf0)
if i click download for the second record ( the browser page is crashed 

### Environment including version

```Markdown
- Beesy: v0.0.14 
- OS: Linux
- Browser: chromed
```

**Comment by Noah-Nelson** [comment]
Hello! I might be encountering the same issue.

- Chromebook (Lenovo ThinkPad C13 Yoga) with ChromeOS v 124.0.6367.219
- Beesy v 0.0.14
- Console error says missing duration

**IMPORTANT**: I forgot to stop the recording before ending the call. Seems a likely source of the problem for me.

Screen capture of download with console output:
[Screen recording 2024-05-23 11.12.45 AM.webm](https://github.com/pi-ra/beesy-issue-tracker/assets/166047252/efa47a69-249e-4dbd-9929-92bd97622a25)

Possibly related, either the Beesy: Recordings tab or sometimes this tab (GitHub) would crash with this or a similar error message if I navigate away from the tab while it is trying to download:
![Screenshot 2024-05-23 11 14 09 AM](https://github.com/pi-ra/beesy-issue-tracker/assets/166047252/360d119a-3ad3-4adc-8841-f71384f4f8dc)

**Comment by piyu-sh** [comment]
Hi @Noah-Nelson ,

Thanks for adding a detailed comment, it really helped.
To clarify a few things:
- Console error says missing duration - You can ignore this warning, it comes up even if video is downloaded
- I forgot to stop the recording before ending the call - Even if you forgot to stop, Beesy still saves the recording in recording tab, so you're safe there, but yes the video size is huge because of that probably
- Possibly related, either the Beesy: Recordings tab or sometimes this tab (GitHub) would crash - yes this might be a problem

So the issue most probably is that the video file is huge, almost 1.5gb and your system is running out of ram when Beesy is trying to process that video in memory that's why the tab crashes when you're trying to download.


Could you please share a few details
- Have you deleted that video from recording tab ? If not, we can still help you retrieve it
- How much ram does your system has ?
- Could you try downloading that video by closing all other programs on your system and all other tabs in the browser ? So the only thing open on your system when that download is running should be chrome with this tab.

**Comment by Noah-Nelson** [comment]
Hi, thanks for the response!

   1. The video is still there. It is my most recent recording from
   Thursday, May 23: beesy_recording-2024_05_23_09_32_03-uwr_hgzj_miw.webm
   2. I have about 4.5 GB available memory out of about 7.75 GB
   3. Unfortunately, closing all other applications and browser tabs did
   *not* do the trick. It still crashed the single chrome tab for Beesy
   recordings without downloading the video file.

**Comment by piyu-sh** [comment]
Hey @Noah-Nelson ,

Great that you haven't deleted it, let me help you download your recording first.
1. Go to the recordings page and open devtools by right clicking anywhere and then clicking 'Inspect' in the context menu
2. Something like this should open up ![image](https://github.com/pi-ra/beesy-issue-tracker/assets/7107647/e76320a0-356b-42fb-947a-27f03edf699f)
3. Click on the `console` panel
4. Now copy paste this code into that `console`
```
(async function downloadFile(fileName){
  const opfsHandle = await navigator.storage.getDirectory()
  const recDir = await opfsHandle.getDirectoryHandle('beesy_recordings')
  const fileToDownloadHandle = await recDir.getFileHandle(fileName);
  const fileToDownload = await fileToDownloadHandle.getFile()
  const ab = await fileToDownload.arrayBuffer();
  const blb = new Blob([ab], {
    type: 'video/webm',
  });
  chrome.downloads.download({url: URL.createObjectURL(blb), filename: fileName});
  
})('your_filename_here')
```
5. Replace 'your_filename_here' in above code with the filename you want to download e.g. 'beesy_recording-2024_04_03_16_46_43-rcs_bqux_qhd.webm'
6. And then press enter, hopefully the recording should start downloading in a minute or so considering its a huge file.

Let me know how it goes.

**Comment by Noah-Nelson** [comment]
Thank you for this, it worked!
Two follow-up questions:

   1. Is there any particular reason the recording did not download locally
   on its own? Would you venture it's because I forgot to end the recording,
   because of the size of it, or something else?
   2. When I bother to record meetings, they tend to be meetings with
   external clients/users, and typically go 1-1.5 hours. This was the case
   with this recording as well. You mentioned that it was quite large. Are
   there other factors I could control to limit video file size besides the
   duration of the recording?

Thanks again for all your help,
Noah

**Comment by piyu-sh** [comment]
Great that you were able to download it ! @Noah-Nelson 

The recording you downloaded might not be seekable in media player(i.e. you would not see the timestamps while playing it).
This is due to browser limitations. To fix this, could you please try to use below option in Beesy settings ?
 
<img width="563" alt="Screenshot 2024-06-01 005731" src="https://github.com/pi-ra/beesy-issue-tracker/assets/7107647/d93a83f0-b309-4d51-a0d3-eb34d41cecf6">


If the browser tab still crashes while fixing this, let me know.


And to your ques:
1. Might be wrong, but I think recordings didn't download because chrome was running out of memory while processing the video. As I mentioned above the video you downloaded wouldn't have timestamps, to fix that we run an operation in memory and that might have caused it to crash.
2.  You can try playing with the video config/audio config settings in Beesy to see if some format is taking up less size. But if you try those, I'd strongly suggest trying them out on *non* important meetings first so you can see if it's the right setting for you.

Rest assured, we'll also be thinking of how to tackle this issue.

**Comment by arunpr90** [comment]
> Hey @Noah-Nelson ,
> 
> Great that you haven't deleted it, let me help you download your recording first.
> 
> 1. Go to the recordings page and open devtools by right clicking anywhere and then clicking 'Inspect' in the context menu
> 2. Click on the `console` panel
> 3. Now copy paste this code into that `console`
> 
> ```
> (async function downloadFile(fileName){
>   const opfsHandle = await navigator.storage.getDirectory()
>   const recDir = await opfsHandle.getDirectoryHandle('beesy_recordings')
>   const fileToDownloadHandle = await recDir.getFileHandle(fileName);
>   const fileToDownload = await fileToDownloadHandle.getFile()
>   const ab = await fileToDownload.arrayBuffer();
>   const blb = new Blob([ab], {
>     type: 'video/webm',
>   });
>   chrome.downloads.download({url: URL.createObjectURL(blb), filename: fileName});
>   
> })('your_filename_here')
> ```
> 
> 4. Replace 'your_filename_here' in above code with the filename you want to download e.g. 'beesy_recording-2024_04_03_16_46_43-rcs_bqux_qhd.webm'
> 5. And then press enter, hopefully the recording should start downloading in a minute or so considering its a huge file.
> 
> Let me know how it goes.

It's working for files than 300mb but now working for files more than 500mb.

When i try to download, the browser stops working / freezer.

**Comment by piyu-sh** [comment]
hey @arunpr90 , sorry for the late reply, could you please help us with a few things ?

- are you still facing this issue ?
- how much ram does your system have ?
- also when you say the system froze, how long was it frozen, or did the browser just closed ?

**Comment by nishant12** [comment]
> Hey @Noah-Nelson ,
> 
> Great that you haven't deleted it, let me help you download your recording first.
> 
> 1. Go to the recordings page and open devtools by right clicking anywhere and then clicking 'Inspect' in the context menu
> 2. Click on the `console` panel
> 3. Now copy paste this code into that `console`
> 
> ```
> (async function downloadFile(fileName){
>   const opfsHandle = await navigator.storage.getDirectory()
>   const recDir = await opfsHandle.getDirectoryHandle('beesy_recordings')
>   const fileToDownloadHandle = await recDir.getFileHandle(fileName);
>   const fileToDownload = await fileToDownloadHandle.getFile()
>   const ab = await fileToDownload.arrayBuffer();
>   const blb = new Blob([ab], {
>     type: 'video/webm',
>   });
>   chrome.downloads.download({url: URL.createObjectURL(blb), filename: fileName});
>   
> })('your_filename_here')
> ```
> 
> 4. Replace 'your_filename_here' in above code with the filename you want to download e.g. 'beesy_recording-2024_04_03_16_46_43-rcs_bqux_qhd.webm'
> 5. And then press enter, hopefully the recording should start downloading in a minute or so considering its a huge file.
> 
> Let me know how it goes.

hi @piyu-sh I am facing the same issue with mp4, the file size 929MB. Page crashes and runs out of memory. Laptop has 16GB of RAM. I tried downloading multiple times and just kept the one tab running on chrome, it still failed.

webm works smoothly for longer meetings.

Please add this code in README. I was going to raise an issue but saw an open issue, code helped me out to download the meeting in webm. Thank you!!

**Comment by piyu-sh** [comment]
Hey @eingdar01 , sorry for the inconvenience. Did you try the solution posted in above thread https://github.com/pi-ra/beesy-issue-tracker/issues/39#issuecomment-2137972550 ?

**Comment by eingdar01** [comment]
Its work!! AMAZING!!!
Thanks a lot!!!

> Hey @eingdar01 , sorry for the inconvenience. Did you try the solution posted in above thread [#39 (comment)](https://github.com/pi-ra/beesy-issue-tracker/issues/39#issuecomment-2137972550) ?

**Comment by Kris-SkyTruth** [comment]
Hi @Noah-Nelson - Just want to say that without the console solution shared in #39 above to download larger videos, I would've left Beesy by now - so THANK YOU for sharing but also I am hopeful other more user-friendly solutions are in progress. I'm a PM (not super comfortable to copy/paste code generally, pretty rare) and hesitate to recommend this product to my less technical peers because I'd be worried this trick to get the meeting to download would be too far beyond their skillsets. I wish I could recommend it more confidently, and with a fix to the large meeting download issue, I would!

**Comment by Noah-Nelson** [comment]
> Hi [@Noah-Nelson](https://github.com/Noah-Nelson) - Just want to say that without the console solution shared in [#39](https://github.com/pi-ra/beesy-issue-tracker/issues/39) above to download larger videos, I would've left Beesy by now - so THANK YOU for sharing but also I am hopeful other more user-friendly solutions are in progress. I'm a PM (not super comfortable to copy/paste code generally, pretty rare) and hesitate to recommend this product to my less technical peers because I'd be worried this trick to get the meeting to download would be too far beyond their skillsets. I wish I could recommend it more confidently, and with a fix to the large meeting download issue, I would!

Thanks for the shoutout @Kris-SkyTruth! I'm happy I could help. I'm also a PM, so I get it. Since I only need to record occasionally, I also plan to keep using Beesy for now thanks to this workaround, but it's not ideal. Not likely to recommend to anyone outside of technical teams unless I know they record only short meetings.

**Comment by rahul-kurup** [comment]
Hey @Noah-Nelson / @Kris-SkyTruth , thank you for raising your concerns. We don't want our users to do workaround for basic functionalities like this. 
As we are a small team, who works on the extension in our spare time, we've already taken a note of the issue at hand. Rest assured we'll provide a simple solution for this in a future release.
Apologies for the delay in bugfix/releases, as there are lots of fixes and goodies in store.
We're polishing everything to provide a good user experience. 
You'll soon hear from us :)

**Comment by rahul-kurup** [comment]
Closing this issue as it should now be resolved with the latest release v0.0.18

**Comment by piyu-sh** [comment]
Re-opening since some users are still facing the issue e.g. https://github.com/pi-ra/beesy-issue-tracker/issues/65

**Comment by rahul-kurup** [comment]
hi @evaldes31 , the syntax is incorrect:

(async function downloadFile(fileName){
 ... rest of the code
})('beesy_recording.....') // NOTICE THE BRACKET AND SINGLE QUOTE AROUND THE RECORDING NAME

------
Alternatively can you tell us, what's the error that you are facing when trying to download the file normally?

**Comment by rahul-kurup** [comment]
@evaldes31 Can you please open a new issue for this? Include details such as when you first noticed the missing audio (microphone) problem. Also, confirm whether your microphone works normally in Google Meet before recording, and describe what changes once the recording starts.

**Comment by piyu-sh** [comment]
Closing since we haven't had anyone report this issue in a long time, if you still think it's happening, please feel free to reopen the issue and share reproduction steps/recording of the issue happening.

**Comment by anna7261** [comment]
> Closing since we haven't had anyone report this issue in a long time, if you still think it's happening, please feel free to reopen the issue and share reproduction steps/recording of the issue happening.

I'm having this issue. I installed Beesy on a fresh brave install. I think the problem is saving the videos as MP4 instead of WebM. The page crashes while trying to encode the video.

<img width="1116" height="1030" alt="Image" src="https://github.com/user-attachments/assets/dcd8fab1-e2ac-48c9-a7e6-ba18d235921e" />

<img width="1116" height="833" alt="Image" src="https://github.com/user-attachments/assets/91f99e99-f69d-4dec-b9d1-c998a4ab1b63" />

**Comment by piyu-sh** [comment]
Reopening the issue.
@anna7261 could you please provide more details:
- what operating system are you on and what version? 
- how much ram does your system have? how much was free when you tried downloading?
- i can see there are multiple files on that list, are you not able to download any fille or only files larger than a particular size?
- are you able to download these files with the workaround shared here https://github.com/pi-ra/beesy-issue-tracker/issues/39#issuecomment-2137972550 ?

>  I think the problem is saving the videos as MP4 instead of WebM.

This should not be the problem, you can check which formats are supported and which is selected from beesy settings

<img width="1306" height="720" alt="Image" src="https://github.com/user-attachments/assets/04abe5e7-9cc1-4d2f-a86d-f930cfef540c" />
